# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [self-hosted, linux]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Update dependencies
      run: echo Updating dependencies... ; bundle update

  deploy:
    runs-on: [self-hosted, linux]
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Start bot
        run: |
          echo Killing previous instance...,
          kill $(pgrep -f bot0.rb) 2> /dev/null && echo Instance killed.
          echo "Loading config"
          cp ~/config/inteam-bot0.json ./config.json
          echo "(Re)Starting bot0..."
          bundle exec ./bot0.rb
